[package]
edition = '2021'
name = "advent_of_code_day9"
version = "1.0.0"
authors = ["Thijs"]

[dependencies]
itertools = "0.10.5"
range-set = "0.0.9"
substring = "1.4.5"
enum-map = "2.4.1"
nalgebra = "0.31.4"
grid = "0.9.0"